interface Data {
  date: string
  description: string
  amount: number
  balance: number
  type: string
  category: string
  notes: string | null
}

export const data: Data[] = [
  {
    date: '23/1/2021',
    description: 'ultrices phasellus id sapien in',
    amount: 76.89,
    balance: 3562.31,
    type: 'duis',
    category: 'mus',
    notes: null,
  },
  {
    date: '9/12/2021',
    description: 'sociis natoque penatibus et magnis',
    amount: 16.13,
    balance: 4299.52,
    type: 'lacus',
    category: 'sem',
    notes: null,
  },
  {
    date: '13/5/2021',
    description: 'donec ut dolor morbi',
    amount: 54.84,
    balance: 8889.57,
    type: 'pellentesque',
    category: 'feugiat',
    notes: null,
  },
  {
    date: '23/6/2021',
    description: 'dapibus augue vel accumsan',
    amount: 74.6,
    balance: 2727.34,
    type: 'consectetuer',
    category: 'fringilla',
    notes: null,
  },
  {
    date: '31/1/2021',
    description: 'convallis duis consequat dui',
    amount: 87.77,
    balance: 6313.84,
    type: 'curae',
    category: 'dolor',
    notes: null,
  },
  {
    date: '10/4/2021',
    description: 'praesent id massa',
    amount: 44.25,
    balance: 2657.06,
    type: 'primis',
    category: 'dolor',
    notes: 'at diam nam tristique tortor',
  },
  {
    date: '22/8/2021',
    description: 'volutpat sapien',
    amount: 82.74,
    balance: 1984.19,
    type: 'non',
    category: 'tempor',
    notes: 'hac habitasse',
  },
  {
    date: '20/5/2021',
    description: 'non mi integer ac neque',
    amount: 6.0,
    balance: 1916.39,
    type: 'mus',
    category: 'interdum',
    notes: 'tempor turpis nec euismod scelerisque quam turpis adipiscing',
  },
  {
    date: '26/2/2021',
    description: 'congue etiam justo etiam',
    amount: 38.8,
    balance: 9926.07,
    type: 'ligula',
    category: 'vestibulum',
    notes: 'hendrerit',
  },
  {
    date: '8/11/2021',
    description: 'laoreet ut rhoncus aliquet',
    amount: 95.63,
    balance: 1584.31,
    type: 'vulputate',
    category: 'adipiscing',
    notes: null,
  },
  {
    date: '22/12/2020',
    description: 'curae mauris viverra diam vitae',
    amount: 51.33,
    balance: 1848.28,
    type: 'metus',
    category: 'etiam',
    notes: null,
  },
  {
    date: '21/9/2021',
    description: 'accumsan tellus nisi eu orci',
    amount: 36.48,
    balance: 1344.73,
    type: 'duis',
    category: 'morbi',
    notes: null,
  },
  {
    date: '1/10/2021',
    description: 'vestibulum',
    amount: 41.27,
    balance: 4733.64,
    type: 'pede',
    category: 'et',
    notes: null,
  },
  {
    date: '14/8/2021',
    description: 'ultrices',
    amount: 57.05,
    balance: 4149.16,
    type: 'luctus',
    category: 'purus',
    notes: null,
  },
  {
    date: '2/5/2021',
    description: 'proin at turpis a pede',
    amount: 27.04,
    balance: 3068.18,
    type: 'luctus',
    category: 'massa',
    notes: 'orci eget orci vehicula condimentum curabitur',
  },
  {
    date: '19/8/2021',
    description: 'eu felis',
    amount: 71.97,
    balance: 50.25,
    type: 'sapien',
    category: 'consectetuer',
    notes: 'vivamus vestibulum sagittis sapien cum sociis',
  },
  {
    date: '11/11/2021',
    description: 'pellentesque ultrices phasellus id',
    amount: 17.61,
    balance: 1104.85,
    type: 'in',
    category: 'vehicula',
    notes: 'ligula nec sem duis aliquam convallis',
  },
  {
    date: '13/2/2021',
    description: 'posuere cubilia curae nulla dapibus',
    amount: 10.95,
    balance: 4185.41,
    type: 'non',
    category: 'elit',
    notes: 'phasellus',
  },
  {
    date: '30/6/2021',
    description: 'consequat',
    amount: 83.44,
    balance: 1767.82,
    type: 'lobortis',
    category: 'turpis',
    notes: 'ut nunc vestibulum ante ipsum primis in faucibus orci',
  },
  {
    date: '15/10/2021',
    description: 'ac nibh fusce',
    amount: 3.45,
    balance: 8334.2,
    type: 'cum',
    category: 'nonummy',
    notes: 'eleifend',
  },
  {
    date: '25/5/2021',
    description: 'neque aenean auctor gravida sem',
    amount: 89.41,
    balance: 8233.68,
    type: 'sed',
    category: 'vehicula',
    notes: 'aliquam quis turpis eget elit sodales scelerisque',
  },
  {
    date: '7/8/2021',
    description: 'commodo placerat praesent',
    amount: 41.62,
    balance: 7485.84,
    type: 'mauris',
    category: 'metus',
    notes: 'lacinia sapien quis libero nullam sit amet',
  },
  {
    date: '26/10/2021',
    description: 'lobortis vel dapibus at',
    amount: 61.81,
    balance: 2300.71,
    type: 'pede',
    category: 'maecenas',
    notes: null,
  },
  {
    date: '6/3/2021',
    description: 'nulla suscipit ligula in lacus',
    amount: 98.38,
    balance: 4553.88,
    type: 'rhoncus',
    category: 'ipsum',
    notes: null,
  },
  {
    date: '25/8/2021',
    description: 'est et tempus semper est',
    amount: 10.56,
    balance: 2290.36,
    type: 'scelerisque',
    category: 'eu',
    notes: null,
  },
  {
    date: '18/1/2021',
    description: 'vivamus',
    amount: 98.61,
    balance: 7998.97,
    type: 'vel',
    category: 'ipsum',
    notes: null,
  },
  {
    date: '12/4/2021',
    description: 'vestibulum ante ipsum',
    amount: 72.95,
    balance: 1656.05,
    type: 'nisi',
    category: 'mauris',
    notes: null,
  },
  {
    date: '28/11/2021',
    description: 'non velit donec',
    amount: 56.33,
    balance: 6357.18,
    type: 'ullamcorper',
    category: 'justo',
    notes: null,
  },
  {
    date: '8/7/2021',
    description: 'sed lacus morbi sem',
    amount: 73.32,
    balance: 2591.97,
    type: 'cubilia',
    category: 'arcu',
    notes: 'quisque erat eros viverra eget congue eget semper rutrum',
  },
  {
    date: '2/1/2021',
    description: 'hac habitasse platea dictumst etiam',
    amount: 66.45,
    balance: 2744.23,
    type: 'mus',
    category: 'enim',
    notes: 'praesent lectus vestibulum quam sapien varius ut blandit',
  },
  {
    date: '9/8/2021',
    description: 'hendrerit at vulputate',
    amount: 64.92,
    balance: 1775.81,
    type: 'amet',
    category: 'platea',
    notes: 'ipsum praesent blandit lacinia erat vestibulum sed magna at nunc',
  },
  {
    date: '7/12/2021',
    description: 'molestie',
    amount: 38.87,
    balance: 8380.34,
    type: 'non',
    category: 'sem',
    notes: 'pede ullamcorper',
  },
  {
    date: '12/10/2021',
    description: 'blandit nam nulla',
    amount: 53.44,
    balance: 8597.06,
    type: 'aliquam',
    category: 'elementum',
    notes: null,
  },
  {
    date: '29/10/2021',
    description: 'amet',
    amount: 4.7,
    balance: 5215.35,
    type: 'nulla',
    category: 'velit',
    notes: 'iaculis congue vivamus metus',
  },
  {
    date: '4/9/2021',
    description: 'maecenas pulvinar lobortis est phasellus',
    amount: 66.23,
    balance: 6805.08,
    type: 'lobortis',
    category: 'pellentesque',
    notes: null,
  },
  {
    date: '10/6/2021',
    description: 'eget orci vehicula',
    amount: 25.38,
    balance: 9963.51,
    type: 'platea',
    category: 'magna',
    notes: null,
  },
  {
    date: '13/2/2021',
    description: 'ligula pellentesque ultrices phasellus',
    amount: 47.29,
    balance: 216.08,
    type: 'turpis',
    category: 'donec',
    notes: 'enim leo rhoncus sed vestibulum sit amet',
  },
  {
    date: '24/6/2021',
    description: 'turpis sed',
    amount: 72.39,
    balance: 7893.95,
    type: 'interdum',
    category: 'luctus',
    notes: null,
  },
  {
    date: '28/3/2021',
    description: 'neque sapien placerat ante',
    amount: 88.5,
    balance: 3730.76,
    type: 'vestibulum',
    category: 'vel',
    notes: 'ligula',
  },
  {
    date: '5/8/2021',
    description: 'eu interdum',
    amount: 42.45,
    balance: 1860.62,
    type: 'blandit',
    category: 'purus',
    notes: 'lacinia aenean sit',
  },
  {
    date: '30/10/2021',
    description: 'molestie sed justo pellentesque',
    amount: 33.89,
    balance: 7995.19,
    type: 'blandit',
    category: 'curae',
    notes: 'cras non velit',
  },
  {
    date: '29/8/2021',
    description: 'aliquam convallis nunc proin',
    amount: 82.13,
    balance: 6485.98,
    type: 'nunc',
    category: 'bibendum',
    notes: null,
  },
  {
    date: '4/5/2021',
    description: 'curabitur at ipsum ac tellus',
    amount: 95.45,
    balance: 7317.54,
    type: 'vivamus',
    category: 'pulvinar',
    notes: 'etiam faucibus cursus urna ut tellus nulla ut erat id',
  },
  {
    date: '14/8/2021',
    description: 'luctus',
    amount: 20.46,
    balance: 1534.14,
    type: 'ipsum',
    category: 'semper',
    notes: null,
  },
  {
    date: '19/8/2021',
    description: 'ligula sit amet eleifend pede',
    amount: 4.62,
    balance: 6188.01,
    type: 'vestibulum',
    category: 'condimentum',
    notes: null,
  },
  {
    date: '25/2/2021',
    description: 'sociis natoque penatibus et magnis',
    amount: 63.61,
    balance: 7167.52,
    type: 'cum',
    category: 'libero',
    notes: 'fermentum donec ut mauris eget massa tempor',
  },
  {
    date: '23/1/2021',
    description: 'bibendum morbi non quam',
    amount: 51.66,
    balance: 9441.39,
    type: 'at',
    category: 'non',
    notes: null,
  },
  {
    date: '22/8/2021',
    description: 'pretium',
    amount: 42.99,
    balance: 8938.14,
    type: 'sit',
    category: 'vel',
    notes: 'vitae mattis nibh ligula',
  },
  {
    date: '7/7/2021',
    description: 'laoreet',
    amount: 97.3,
    balance: 709.17,
    type: 'in',
    category: 'consequat',
    notes: null,
  },
  {
    date: '16/10/2021',
    description: 'nisl aenean lectus',
    amount: 93.61,
    balance: 9918.04,
    type: 'ullamcorper',
    category: 'at',
    notes: null,
  },
]
